se sts=4 sw=4 so=5 ls=2 nu rnu et hls mouse=a is ic scs
filetype indent on |imap jk <Esc> |map <C-l> :nohl<CR>
nmap <F9> :!make R=$(basename % .cpp)<CR>|map ; :
ca hash w !cpp -dD -P -fpreprocessed \| tr -d '[:space:]' \| md5sum \| cut -c-6
" setarch `uname -m` -R /bin/bash; set -g mode-keys vi
" alias cp='cp -i'; setxkbmap -option ctrl:nocaps; xmodmap
