set ts=4 sw=4 nu rnu et cin hls mouse=a
color default
sy on
inoremap {<CR> {<CR>}<C-o>O
inoremap jk <Esc>
nnoremap J 5j
nnoremap K 5k
nnoremap <F8> :w<bar>!g++ -std=c++20 -DLOCAL -Wfatal-errors -Wshadow -O2 -g -fsanitize=address,undefined -o run "%" && echo "done." && time ./run<CR>